const regHotelModel = {
    hotelIdx: 0,
    nameKo: "",
    nameEn: "",
    nationType: "",
    nameKey: "",
    hotelStatus: "",
    branchType: "900",
    buildType: "000",
    positionType: "",
    homePage: "",
    homePageShowYn: "",
    grade: 0,
    goodCount: 0,
    viewCount: 0,
    zipcode: "",
    addr1Ko: "",
    addr1En: "",
    addr2Ko: "",
    addr2En: "",
    latitude: "",
    longitude: "",
    interPhoneNumber: "",
    phone1: "",
    phone2: "",
    phone3: "",
    checkInTime: "",
    checkOutTime: "",
    infoKo: "",
    infoEn: "",
    ruleKo: "",
    ruleEn: "",
    // personInfo: [
    //     {
    //         hotelIdx: 0,
    //         personName: "",
    //         phone: "",
    //         email: "",
    //         position: "",
    //         memo: "",
    //         useYn: "",
    //         delYn: "",
    //         showYn: "",
    //         userIdx: 0,
    //         userNameKo: "",
    //         userNameEn: "",
    //         regUserIdx: 0,
    //         regUserNameKo: "",
    //         regUserNameEn: "",
    //         regDttm: "",
    //         modUserIdx: 0,
    //         modUserNameKo: "",
    //         modUserNameEn: "",
    //         modDttm: "",
    //     },
    // ],
    // priceInfo: [
    //     {
    //         hotelIdx: 0,
    //         roomIdx: 0,
    //         priceType: "",
    //         priceDiv: "",
    //         priceMemo: "",
    //         originPrice: "",
    //         orgStart: "",
    //         orgEnd: "",
    //         salePrice: "",
    //         saleRate: "",
    //         saleStart: "",
    //         saleEnd: "",
    //         useYn: "",
    //         delYn: "",
    //         showYn: "",
    //         userIdx: 0,
    //         userNameKo: "",
    //         userNameEn: "",
    //         regUserIdx: 0,
    //         regUserNameKo: "",
    //         regUserNameEn: "",
    //         regDttm: "",
    //         modUserIdx: 0,
    //         modUserNameKo: "",
    //         modUserNameEn: "",
    //         modDttm: "",
    //     },
    // ],
    // additionalInfo: [
    //     {
    //         hotel_idx: 0,
    //         key_name: "",
    //         additional_name_ko: "",
    //         additional_name_en: "",
    //         additional_memo: "",
    //         useYn: "",
    //         delYn: "",
    //         showYn: "",
    //         userIdx: 0,
    //         userNameKo: "",
    //         userNameEn: "",
    //         regUserIdx: 0,
    //         regUserNameKo: "",
    //         regUserNameEn: "",
    //         regDttm: "",
    //         modUserIdx: 0,
    //         modUserNameKo: "",
    //         modUserNameEn: "",
    //         modDttm: "",
    //     },
    // ],
    // attachmentOrgFile: [{}],
    // attachmentThumbFile: [{}],
    useYn: "",
    delYn: "",
    showYn: "",
    userIdx: 0,
    userNameKo: "",
    userNameEn: "",
    regUserIdx: 0,
    regUserNameKo: "",
    regUserNameEn: "",
    regDttm: "",
    modUserIdx: 0,
    modUserNameKo: "",
    modUserNameEn: "",
    modDttm: "",
};

const hotel_static = {
    NATION_TYPE: {
        domestic: "000",
        overseas: "100",
        convertKo: {
            "000": "국내",
            100: "해외",
        },
    },
};

export { regHotelModel, hotel_static };
