const roomModel = {
    roomIdx: 0,
    hotelIdx: 0,
    nameKo: "",
    nameEn: "",
    roomNumber: "",
    roomSize: "",
    minPeople: 0,
    maxPeople: 0,
    infoKo: "",
    infoEn: "",
    ruleKo: "",
    ruleEn: "",
    rowNum: 0,
    useYn: "",
    delYn: "",
    multipleYn: "",
    showYn: "",
    userIdx: 0,
    userNameKo: "",
    userNameEn: "",
    regUserIdx: 0,
    regUserNameKo: "",
    regUserNameEn: "",
    regDttm: "",
    modUserIdx: 0,
    modUserNameKo: "",
    modUserNameEn: "",
    modDttm: "",
};

const room_static = {
    additional_type: "100",
    bed_type: {
        "000": "싱글",
        "050": "슈퍼싱글",
        100: "더블",
        150: "세미 더블",
        200: "퀸",
        300: "킹",
        350: "라지킹",
        400: "간이침대",
        500: "유아용 침대",
        800: "온돌",
        900: "기타",
    },
    file_origin_type_cd: {
        thumb: "100",
        origin: "000",
    },
};

export { roomModel, room_static };
